version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/task_db
    networks:
      - my_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend_vue
    depends_on:
      - backend
    ports:
      - "8501:80"
    environment:
      - VUE_APP_BACKEND_URL=http://backend:5000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
